import Head from "next/head";

import styles from "../styles/home.module.css";

import Jumbotron from "../components/Jumbotron";
import Navbar from "../components/Navbar";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Adopt a Cat</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Navbar />
				<Jumbotron />
			</main>
		</div>
	);
}
